// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfVTgxctXLc0NAGSQ6SAhNDovpgjQxe54',
    appId: '1:92598071273:web:6f905905966f8763ce2578',
    messagingSenderId: '92598071273',
    projectId: 'nexplay-np1',
    authDomain: 'nexplay-np1.firebaseapp.com',
    storageBucket: 'nexplay-np1.firebasestorage.app',
    measurementId: 'G-KG68Y9WF0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBewbuYl_qjew1xN863_ExEERoMdnu6ky8',
    appId: '1:92598071273:android:72d62240d56e80d3ce2578',
    messagingSenderId: '92598071273',
    projectId: 'nexplay-np1',
    storageBucket: 'nexplay-np1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSRTvOoUj72jqxkmIlZpUj1kdP9L8nrgk',
    appId: '1:92598071273:ios:c18ed1769cf61948ce2578',
    messagingSenderId: '92598071273',
    projectId: 'nexplay-np1',
    storageBucket: 'nexplay-np1.firebasestorage.app',
    iosClientId: '92598071273-in5r56h6cd8f8qr7m4j8rl0g5kb3lmio.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSRTvOoUj72jqxkmIlZpUj1kdP9L8nrgk',
    appId: '1:92598071273:ios:c18ed1769cf61948ce2578',
    messagingSenderId: '92598071273',
    projectId: 'nexplay-np1',
    storageBucket: 'nexplay-np1.firebasestorage.app',
    iosClientId: '92598071273-in5r56h6cd8f8qr7m4j8rl0g5kb3lmio.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfVTgxctXLc0NAGSQ6SAhNDovpgjQxe54',
    appId: '1:92598071273:web:f00b992db76ea49dce2578',
    messagingSenderId: '92598071273',
    projectId: 'nexplay-np1',
    authDomain: 'nexplay-np1.firebaseapp.com',
    storageBucket: 'nexplay-np1.firebasestorage.app',
    measurementId: 'G-02Z0B76W84',
  );
}
